# Generated by Django 6.0.4 on 2026-04-22 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Connectiviter_type', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('PANNE', 'Panne'), ('MAINTENANCE', 'Maintenance'), ('DECONNECTE', 'Déconnecté')], default='INACTIF', max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUEL', 'Manuel')], default='AUTO', max_length=20)),
                ('Bactterie', models.IntegerField()),
                ('Adresse_IP', models.GenericIPAddressField()),
                ('Temp_restante', models.DateField()),
                ('Date_dernier_maintenance', models.DateField()),
                ('Date_dernier_utilisation', models.DateField()),
                ('Description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/outils/')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20)),
                ('type_membre', models.CharField(choices=[('citoyen', 'Citoyen'), ('etudiant', 'Etudiant'), ('technicien', 'Technicien'), ('administrateur', 'administrateur')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/personne/')),
                ('date_naissance', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
