# Generated by Django 6.0.4 on 2026-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='type_membre',
            field=models.CharField(blank=True, choices=[('citoyen', 'Citoyen'), ('etudiant', 'Etudiant'), ('technicien', 'Technicien'), ('administrateur', 'administrateur')], max_length=20, null=True),
        ),
    ]
