# Generated by Django 6.0.4 on 2026-04-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_alter_personne_age_alter_personne_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='nb_actions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personne',
            name='nb_connexions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personne',
            name='niveau',
            field=models.CharField(default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='personne',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='personne',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personne',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=10),
        ),
        migrations.AlterField(
            model_name='personne',
            name='type_membre',
            field=models.CharField(choices=[('visiteur', 'visiteur'), ('simple', 'simple'), ('complexe', 'complexe'), ('administrateur', 'administrateur')], default='visiteur', max_length=30),
        ),
    ]
