# Generated by Django 6.0.4 on 2026-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_personne_nb_actions_personne_nb_connexions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='type_membre',
            field=models.CharField(choices=[('visiteur', 'Visiteur'), ('simple', 'Simple'), ('complexe', 'Complexe'), ('administrateur', 'Administrateur')], default='visiteur', max_length=30),
        ),
    ]
