# Generated by Django 6.0.4 on 2026-04-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_alter_personne_type_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/information/')),
                ('date', models.DateField(auto_now_add=True)),
                ('auteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Information_locale',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monapp.information')),
            ],
            bases=('monapp.information',),
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monapp.information')),
            ],
            bases=('monapp.information',),
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/lieux/')),
                ('liste_produits', models.ManyToManyField(related_name='lieux', to='monapp.produit')),
            ],
        ),
    ]
