# Generated by Django 6.0.4 on 2026-04-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_information_information_locale_signalement_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='monapp.lieu'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='monapp.produit'),
        ),
        migrations.AddField(
            model_name='signalement',
            name='type_signalement',
            field=models.CharField(choices=[('accident', 'Accident'), ('danger', 'Danger'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
