# Generated by Django 6.0.4 on 2026-04-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0007_demandepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='email_confirme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personne',
            name='token_confirmation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
